# plotting functions for visualization of Allele-specific DNase and TFs
# ZZ, 2020.2.25

library(ggplot2)
source("./R/darts_theme.R")
library(PRROC)
library(reshape2)
library(dplyr)
library(ggpubr)


# a designated function for converting names
name_mapping_func = function(df)
{
	dict = c(
		"CHR"= "chr",
		"POS"= "pos",
		"REF"= "ref",
		"ALT"= "alt",
		"Ref.reads" = "ref_reads",
		"Alt.reads" = "alt_reads",
		"new_cell_type"= "deepsea_col",
		"tf" = "target",
		"Cell.type"="target"
	)
	colname_idx = which( colnames(df) %in% names(dict) )
	if (length(colname_idx))
		   colnames(df)[colname_idx] = dict[ colnames(df)[colname_idx]  ]
	return(df)
}


# reader for TSV generated by Snakemake
read_summary_data = function(fp)
{
	data = read.table(fp, sep="\t", header=T, stringsAsFactors=F)
	data = name_mapping_func(data)

	data$total_reads = data$ref_reads + data$alt_reads
	data$ratio = data$ref_reads / data$total_reads
	data$pred_margin = data$Ref_pred - data$Alt_pred

	data$obs_label = NA
	data$obs_label[data$ratio>0.6] = 1
	data$obs_label[data$ratio<0.4] = -1
	data$pred_label = ifelse(data$pred_margin>0, 1, -1)

	if (! "p_binomial" %in% colnames(data))
	{
		data$p_binomial = NA
		for(i in 1:nrow(data))
			data$p_binomial[i] = binom.test(x=data$ref_reads[i], n=data$total_reads[i], p=0.5)$p.value
	}

	if (! "fdr_binomial" %in% colnames(data))
		data$fdr_binomial = p.adjust(data$p_binomial, method="fdr")

	#data = data[which(data$p_binomial<0.01 & data$total_reads > 50), ]
	
	return(data)
}



# evaluate and plot performance w.r.t. distinguishing Gain/Loss-of-function alleles
compute_overall_acc = function(input_search_fp, input_random_fp, out_fp, data_fn)
{

	get_accuracy_overall = function(data, margins=seq(0,0.4,0.05))
	{
		res_df = NULL
		this = data
		for(j in 1:length(margins))
		{
			margin = margins[j]
			idx = which( abs(this$pred_margin)>margin )
			if(! length(idx)) next
			acc = mean( this$obs_label[idx]==this$pred_label[idx], na.rm=T )
			if(is.nan(acc)) next
			
			# for asymptotic ci
			num_total = sum(!is.na(this$obs_label[idx]))
			std = sqrt( acc*(1-acc) / num_total )

			res_df = rbind.data.frame(res_df, 
						  data.frame( 
							     margin=margin, 
							     acc=acc,
							     num_correct=sum( this$obs_label[idx]==this$pred_label[idx], na.rm=T ),
							     num_total=num_total, 
							     ci_upper=acc+1.96*std,
							     ci_lower=acc-1.96*std
							     ) 
			)

		}

		return(res_df)
	}

	raw.s = read_summary_data(input_search_fp)
	# NOTE: Need to re-examine those magic numbers in filtering
	# ZZ. 2020.3.29
	raw.s = raw.s[which(raw.s$p_binomial<0.01 & raw.s$total_reads>50),]
	raw.r = read_summary_data(input_random_fp)
	raw.r = raw.r[which(raw.r$p_binomial<0.01 & raw.r$total_reads>50),]
	df.s = get_accuracy_overall(raw.s)
	df.r = get_accuracy_overall(raw.r)
	
	df.s$category = 'BioNAS'
	df.r$category = 'SampArch'
	
	margin_to_plot = as.factor(c(0, 0.05, 0.1))
	df.s0 = df.s[as.factor(df.s$margin) %in% margin_to_plot,]
	df.r0 = df.r[as.factor(df.r$margin) %in% margin_to_plot,]

	pvals = c()
	for(i in 1:nrow(df.s0))
	{
		cont_table = matrix(c( df.s0$num_correct[i], df.s0$num_total[i], df.r0$num_correct[i], df.r0$num_correct[i] ), nrow=2, ncol=2)
		pvals = c(pvals, fisher.test(cont_table)$p.value)
	}

	df = rbind.data.frame(df.s0, df.r0)
	df$category = factor(df$category, levels=c("BioNAS", "SampArch"))
	#df$margin = factor(df$margin )
	dodge = 0.025
	p = ggplot(aes(x=margin, y=acc, colour=category), data=df) + geom_point(position=position_dodge(width = dodge), size=2) + 
		geom_errorbar(aes(ymin=ci_lower, ymax=ci_upper), width=0.0, position=position_dodge(dodge)) + 
		scale_colour_manual(values=c("red", "black")) + 
		#geom_line(linetype="dashed", position=position_dodge(dodge)) + 
		ylab("Accuracy") + xlab("Prediction Margin") + 
		scale_x_continuous(breaks=c(0, 0.05, 0.1)) + 
		Darts_theme +
		theme(legend.position=c(1,0), legend.justification=c(1,0), legend.title=element_blank()) + 
		annotate("text", x=c(0, 0.05, 0.1), y=1, label=formatC(pvals, format="e", digits=2) )

	if(!is.null(data_fn)) write.table(df, file=data_fn, sep="\t", quote=F, row.names=F )
	
	ggsave(p,file=out_fp, width=4.5, height=4.5)
}



# plot the AUC performance for Gain and Loss alleles w.r.t. background alleles
# also evaluate against baseline methods
compute_group_auc = function(input_search_fp, input_random_fp, out_gain_fp, out_loss_fp)
{
	raw = read_summary_data(input_search_fp)
	raw2 = read_summary_data(input_random_fp)
	stopifnot( nrow(raw)==nrow(raw2)) 

	data = raw[, c("chr", "pos", "ref", "alt", "target", "ref_reads", "alt_reads", "total_reads", "fdr_binomial", "deepsea_col")]
	data$ratio = data$ref_reads / data$total_reads
	
	if(! "ds_logfc" %in% colnames(raw)) 
	{
		print("Cannot find required column 'deepsea' - skip this analysis")
		return(NA)
	}

	data$nas.search = log(raw$Alt_pred/(1-raw$Alt_pred)) - log(raw$Ref_pred/(1-raw$Ref_pred))
	data$nas.random = log(raw2$Alt_pred/(1-raw2$Alt_pred)) - log(raw2$Ref_pred/(1-raw2$Ref_pred))
	data$deepsea = raw$ds_logfc
	data$deltasvm = raw$deltasvm
	data$deepbind = raw$deepbind_max_delta_raw
	data$jaspar = raw$jaspar_max_delta_raw
	data$meme = raw$best_meme_max_delta_raw


	data$obs_label = NA
        data$obs_label[which(data$ratio>0.6 & data$fdr_binomial<0.01) ] = 1
        data$obs_label[which(data$ratio<0.4 & data$fdr_binomial<0.01) ] = -1
	data$obs_label[data$fdr_binomial>0.9] = 0

        data = data[ which( (data$ref_reads>10 | data$alt_reads>10) & !is.na(data$obs_label)) ,]

	auc_sum_func = function(obs, pred, type="pos"){
		if(type=="pos"){
			scores0 = - pred[which(obs==0 & !is.na(pred) )]
			scores1 = - pred[which(obs==1 & !is.na(pred) )]
		} else {
			scores0 = pred[which(obs==0 & !is.na(pred) )]
			scores1 = pred[which(obs==-1 & !is.na(pred) )]
		}
		if(length(scores1)<20 || length(scores0)<20) {
			return(NA)
		} else {
			auc = roc.curve(scores.class0=scores1, scores.class1=scores0, curve=F)
			return(auc$auc)
		}
	}
	
	tidy_summarize_auc = function(type){
		res = as.data.frame(
		data %>% 
		group_by(deepsea_col) %>%
		summarize(
			  nas.search = auc_sum_func(obs=obs_label, pred=nas.search, type=type),
			  nas.random = auc_sum_func(obs=obs_label, pred=nas.random, type=type),
			  deepsea = auc_sum_func(obs=obs_label, pred=deepsea, type=type),
			  deltasvm = auc_sum_func(obs=obs_label, pred=deltasvm, type=type),
			  deepbind = auc_sum_func(obs=obs_label, pred=deepbind, type=type),
			  jaspar = auc_sum_func(obs=obs_label, pred=jaspar, type=type),
			  meme = auc_sum_func(obs=obs_label, pred=meme, type=type)
		)	
		)
		res0 = as.matrix(res[,-1])
		print(apply(res0, 2, function(x) median(x, na.rm=T)) )
		return(res)
	}
	# updated on 2020.3.5: using `ggpubr`, add p-values
	res1 = tidy_summarize_auc(type="pos")
	res2 = tidy_summarize_auc(type="neg")
	my_comparisons <- list( c("nas.search", "nas.random")
			       #c("nas.search", "deepsea"),
			       #c("nas.search", "deltasvm"),
			       #c("nas.search", "deepbind")
       	)
	idx0.1 = which(apply(is.na(res1[,-1]), 1, sum)!=ncol(res1)-1)
	res0.1 = res1[idx0.1, ]
	res0.1 = melt(res0.1)
	p0.1 = ggboxplot(x="variable", y="value", color="variable", data=res0.1, outlier.shape=NA ) +
		stat_compare_means(comparisons = my_comparisons, method="wilcox.test", paired=T) +
                scale_x_discrete(limits = rev(levels(res0.1$variable)), 
				 labels=rev(c("BioNAS","SampArch", "DeepSEA", "deltaSVM", "DeepBind", "Jaspar", "MEME"))) +
                #scale_y_continuous(breaks=seq(0.4,0.9,0.1), labels=seq(0.4, 0.9, 0.1)) +
                xlab("") + ylab("AUROC") +
                coord_flip() +
                Darts_theme +
                theme(axis.text.y = element_text(angle=0, hjust=1),  legend.title=element_blank(), legend.position="none") +
                geom_hline(yintercept=seq(0.4, 0.9, 0.1), linetype="dashed", colour="grey")

	idx0.2 = which(apply(is.na(res2[,-1]), 1, sum)!=ncol(res2)-1)
	res0.2 = res2[idx0.2, ]
	res0.2 = melt(res0.2)
	p0.2 = ggboxplot(x="variable", y="value", color="variable", data=res0.2, outlier.shape=NA) +
		stat_compare_means(comparisons = my_comparisons, method="wilcox.test", paired=T) +
                scale_x_discrete(limits = rev(levels(res0.1$variable)), 
				 labels=rev(c("BioNAS", "SampArch", "DeepSEA", "deltaSVM", "DeepBind", "Jaspar", "MEME"))) +
                #scale_y_continuous(breaks=seq(0.4,0.9,0.1), labels=seq(0.4, 0.9, 0.1)) +
                xlab("") + ylab("AUROC") +
                coord_flip() +
                Darts_theme +
                theme(axis.text.y = element_text(angle=0, hjust=1),  legend.title=element_blank(), legend.position="none") +
                geom_hline(yintercept=seq(0.4, 0.9, 0.1), linetype="dashed", colour="grey")


	ggsave(p0.1, file=out_gain_fp, width=4.5, height=4.5)
	ggsave(p0.2, file=out_loss_fp, width=4.5, height=4.5)

}



parser = function()
{
	args = commandArgs(T)
	input_search_fp = args[1]
	input_random_fp = args[2]
	output_prefix = args[3]

	# analysis 1
	out1 = paste0(output_prefix, ".gain.group_auc.pdf")
	out2 = paste0(output_prefix, ".loss.group_auc.pdf")
	compute_group_auc(input_search_fp, input_random_fp, out1, out2)

	# analysis 2
	out3 = paste0(output_prefix, ".overall_acc.pdf")
	out4 = paste0(output_prefix, ".overall_acc.tsv")
	compute_overall_acc(input_search_fp, input_random_fp, out3, out4)
}


parser()
